# Generated by Django 4.1.5 on 2023-08-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='owner',
        ),
    ]
