# Generated by Django 4.1.5 on 2023-08-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_user_cart_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='completed',
        ),
    ]
