# Generated by Django 4.1.5 on 2023-09-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_category_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_product',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product', unique=True),
        ),
    ]
