# Generated by Django 4.1.5 on 2023-09-01 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0005_alter_favourite_product_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_product',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite_product',
            unique_together={('owner', 'Product')},
        ),
    ]
